name: buildpack_dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.8.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner:
  dart_flutter_team_lints: ^1.0.0
  json_serializable:
  shelf_hotreload: ^1.0.1
