name: buildpack_dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.6.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner:
  json_serializable:
  lints: ^2.0.0
  shelf_hotreload: ^1.0.1
